#
# ReSharper.WixToolset
# AppVeyor configuration
#

version: 0.1.0.{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2015

platform: Any CPU
configuration:
  - Debug
  - Release

build:
  project: ReSharper.WixToolset.sln
  verbosity: minimal

before_build:
  - appveyor-retry nuget restore

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'

cache:
  - packages -> **\packages.config
